### ISSUE TITLE
500 error with SoloKey authenticator

### ISSUE THREAD

**Issue by loxlay** [akeeba/passwordless#1]
Hi
I tried to register a SoloKey Secure (USB-Stick) as authenticator and got the error 500.
Chrome recognized the SoloKey correct, but I wasn’t able to register this authenticator to my user in Joomla. 
https://www.rk-mediawork.de/kunden/joomlatest/500error.PNG 
There was nothing in the Joomla logs.
Joomla: 3.9.10
PHP: 7.2.11
Chrome: 76
Windows: 10 64 Bit

Any idea?
Thanks
Robin

**Comment by nikosdion** [comment]
Please open a new issue using the Bug Report template. Provide all information requested in the template. Thank you in advance for helping me help you.
