### ISSUE TITLE
missing language string?

### ISSUE THREAD

**Issue by brianteeman** [akeeba/passwordless#7]
afaict the language string for this error message is not present

https://github.com/akeeba/passwordless/blob/e3aa8ef25ad5aa7f8938df7f6b777962a4f30eb4/plugins/system/passwordless/src/PluginTraits/AjaxHandler.php#L69

I guess it should be something like

PLG_SYSTEM_PASSWORDLESS_ERR_AJAX_INVALIDACTION="Invalid ajax action"

**Comment by nikosdion** [comment]
Yes, that is a missing string. Can you please do a PR?

FWIW this should never happen. There is no AJAX URL generated internally that does not have an `akaction`. If you reach that trap it means that either someone was trying to fuzz the input to see if they can attack WebAuthn login (they can't), or a 3PD plugin or server configuration screwed up. If you can convey that in a sentence please do. I tried, I failed, and then forgot I had not yet written anything for that lang string 🙈

**Comment by brianteeman** [comment]
closed see #8
